'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import Image from 'next/image';
import { ArrowRight, Bot, Layers, Users, Ruler } from 'lucide-react';
import { Button } from '@/components/ui/button';

const features = [
  {
    title: 'AI Design Studio',
    description: 'The heart of TioraS. Generate unique patterns and graphics with simple text prompts.',
    icon: <Bot className="size-8 text-primary" />,
    href: '/design-studio',
    cta: 'Start Creating',
    className: 'md:col-span-2 md:row-span-2',
    image: '/assets/ai-studio-bg.png',
  },
  {
    title: 'Premium Collections',
    description: 'Curated designs generated by our top AI models and community artists.',
    icon: <Layers className="size-8 text-purple-500" />,
    href: '/catalog',
    cta: 'Browse Store',
    className: 'md:col-span-1 md:row-span-1',
  },
  {
    title: 'Community',
    description: 'Join a global network of creators. Share, remix, and inspire.',
    icon: <Users className="size-8 text-blue-500" />,
    href: '/community',
    cta: 'Join Us',
    className: 'md:col-span-1 md:row-span-1',
  },
  {
    title: 'Custom Fit',
    description: 'AI-driven sizing ensures your custom piece fits perfectly, every time.',
    icon: <Ruler className="size-8 text-green-500" />,
    href: '/sizing',
    cta: 'Learn More',
    className: 'md:col-span-2 md:row-span-1',
  },
];

export function FeatureShowcase() {
  return (
    <section className="bg-secondary/20 py-24 md:py-32">
      <div className="container px-4 md:px-6">
        <div className="mb-16 text-center">
          <h2 className="font-headline text-3xl font-bold tracking-tight sm:text-4xl md:text-5xl">
            The Platform
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            Everything you need to express yourself.
          </p>
        </div>

        <div className="grid gap-4 md:grid-cols-4 md:grid-rows-2">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, scale: 0.95 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: index * 0.1 }}
              className={`group relative overflow-hidden rounded-3xl border bg-background/50 p-8 transition-all hover:bg-accent/50 ${feature.className}`}
            >
              {feature.image && (
                <div className="absolute inset-0 z-0 opacity-40 transition-opacity group-hover:opacity-60">
                  <Image
                    src={feature.image}
                    alt={feature.title}
                    fill
                    className="object-cover transition-transform duration-700 group-hover:scale-110"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-background via-background/20 to-transparent"></div>
                </div>
              )}
              
              <div className="absolute top-0 right-0 -mt-4 -mr-4 size-32 rounded-full bg-gradient-to-br from-primary/10 to-transparent blur-2xl transition-all group-hover:scale-150"></div>
              
              <div className="relative z-10 flex h-full flex-col justify-between">
                <div>
                  <div className="mb-4 inline-flex rounded-2xl bg-background p-3 shadow-sm">
                    {feature.icon}
                  </div>
                  <h3 className="mb-2 font-headline text-2xl font-bold">{feature.title}</h3>
                  <p className="text-muted-foreground max-w-[280px]">{feature.description}</p>
                </div>
                
                <div className="mt-8">
                  <Button asChild variant="ghost" className="group-hover:translate-x-1 transition-transform p-0 hover:bg-transparent">
                    <Link href={feature.href} className="flex items-center text-primary font-bold">
                      {feature.cta} <ArrowRight className="ml-2 size-4" />
                    </Link>
                  </Button>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
